server:
  servlet:
    context-path: /speedtest/
  port: 5003
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: always

spring:
  config:
    import: "C:/Users/Suraj.000/IdeaProjects/hotifi-service-v2/src/main/resources/application.yaml"